name: Go

on:
  push:
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: node:10.16-jessie
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: test
      run: |
        git log
